armv8.c: add HYP mode to armv8_mode_data
Hyp mode was not listed in armv8_mode_data.
When CPSR & 0x1F == 0x1A, this causes:

Error: unrecognized psr mode: 0x1a
Debug: set CPSR 0x600001da: UNRECOGNIZED mode, AArch32 state  

Change-Id: I182f0340580b76511c27832e56b39d584e826fcc
Signed-off-by: Tarek BOCHKATI <tarek.bouchkati@gmail.com>